### PR TITLE
Draft: Added polish translation - originally prepared for v4 by http://athka…

### PR DESCRIPTION
**Pull request by lukasz-pekala**
Added polish translation - originally prepared for v4 by http://athkatla.cob-bg.pl/ community

I need help with the installation however. When I try to install it:

```
Install Component [Back to Brynnlaw mod do Baldur's Gate II]?
[I]nstall, or [N]ot Install or [Q]uit? i

Installing [Back to Brynnlaw mod do Baldur's Gate II] [v8]
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Back to Brynnlaw mod do Baldur's Gate II], rolling back to previous state
Will uninstall   0 files for [BACKBRYNNLAW/BACKBRYNNLAW.TP2] component 0.
Uninstalled      0 files for [BACKBRYNNLAW/BACKBRYNNLAW.TP2] component 0.
**ERROR: Unix.Unix_error(20, "opendir", "")**
Please make a backup of the file: SETUP-BACKBRYNNLAW.DEBUG and look for support at: http://forums.pocketplane.net
Using Language [Polski tlum. przez http://athkatla.cob-bg.pl/viewtopic.php?t=6760]

```

I'm installing this on windows

### CODE REVIEW

**Comment by Gitjas** [comment]
Cool! Are you one of the original translators, or do they know about this? Also, do you have a forum name by which I know you? :)

**Comment by lukasz-pekala** [comment]
Hi no I'm not one of the original translators. My work was restricted to opening this PR
Original thread from the forum is here: http://athkatla.cob-bg.pl/viewtopic.php?p=118857

I should have asked them before opening this PR. I will ask them under the thread mentioned above.

"Also, do you have a forum name by which I know you? :)"
Rather not :) I'm not sure which forum you're talking about but I'm not registered in any BG-related forums (except http://athkatla.cob-bg.pl).


1. Let's wait for the permission first
2. I will also add readme files to the translation if the community agrees
3. **ERROR: Unix.Unix_error(20, "opendir", "")** has to be resolved first. @Gitjas any ideas how to solve it?

**Comment by Gitjas** [comment]
1.,2. sound good, thanks!
3. not really - might it be possible that weidu lacks the rights to write to the folders? - Windows is very protective. Did you try copying the game folder to another drive than C: and mod the copied game?

**Comment by lukasz-pekala** [comment]
Translation group decided to update this translation to the current version of their mod on their own

**Pull request closed without merging**
